---
- name: Install fail2ban. (Debian)
  apt: name=fail2ban state=present
  when: ansible_os_family == 'Debian'

- name: Install fail2ban. (RedHat)
  package:
    name: fail2ban
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes
