---
- name: Install fail2ban.
  apt: name=fail2ban state=present
  when: ansible_os_family == 'Debian'

- name: Install fail2ban.
  yum: name=fail2ban state=present enablerepo=epel
  when: ansible_os_family == 'RedHat'

- name: Ensure fail2ban is running and enabled on boot.
  service: name=fail2ban state=started enabled=yes
