---
- name: ensure log watcher is installed. (Debian)
  apt: name=logwatch state=present
  when: ansible_os_family == 'Debian'

- name: ensure log watcher is installed. (RedHat)
  package:
    name: logwatch
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: remove different naming of log watch cron job file
  shell: rm -f /etc/cron.daily/*logwatch*
  args:
    warn: false

- name: setup log watcher mailer.
  template: src=etc/cron.daily/00logwatch.j2 dest=/etc/cron.daily/00logwatch owner=root group=root mode=0755
