---
# tasks file for ansible-role-security
# Load a variable file based on the OS family
- include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: cron.yml
  when: security_cron_enabled

- include_tasks: autoupdate-{{ ansible_os_family }}.yml
  when: security_autoupdate_enabled

- include_tasks: fail2ban.yml
  when: security_fail2ban_enabled

- include_tasks: logwatch.yml
  when: security_logwatch_enabled

- include_tasks: mail.yml

- include_tasks: ssh.yml
