---
# tasks file for ansible-role-security
# Load a variable file based on the OS family
- include_vars: "{{ ansible_os_family }}.yml"

- include: cron.yml
  when: security_cron_enabled

- include: autoupdate-{{ ansible_os_family }}.yml
  when: security_autoupdate_enabled

- include: fail2ban.yml
  when: security_fail2ban_enabled

- include: logwatch.yml
  when: security_logwatch_enabled

- include: mail.yml

- include: ssh.yml
