---
# handlers file for ansible-role-security
- name: reload aliases
  command: newaliases

- name: restart ssh
  service: name="{{ security_sshd_name }}" state=restarted

- name: reload unattended-upgrades
  service: name=unattended-upgrades state=restarted
